// Thin wrapper around window.api exposed by preload.js
// Provides clean imports and a centralized place for error handling

const api = window.api

export const openDirectory = () => api.openDirectory()
export const scanDirectory = (dirPath) => api.scanDirectory(dirPath)
export const readFile = (filePath) => api.readFile(filePath)
export const writeFile = (filePath, content) => api.writeFile(filePath, content)
export const deleteFile = (filePath) => api.deleteFile(filePath)
export const renameFile = (oldPath, newPath) => api.renameFile(oldPath, newPath)
export const getLastDirectory = () => api.getLastDirectory()
export const configSet = (key, val) => api.configSet(key, val)
export const configGet = (key, defaultVal) => api.configGet(key, defaultVal)
export const secureSet = (key, val) => api.secureSet(key, val)
export const secureGet = (key) => api.secureGet(key)
export const setClaudeKey = (key) => api.setClaudeKey(key)
export const getClaudeKey = () => api.getClaudeKey()
export const setOpenAIKey = (key) => api.setOpenAIKey(key)
export const getOpenAIKey = () => api.getOpenAIKey()
export const openImage = () => api.openImage()
export const aiListModels = () => api.aiListModels()
export const aiSuggestImagePrompts = (text) => api.aiSuggestImagePrompts(text)
export const aiSuggestTextStyle = (text, desc) => api.aiSuggestTextStyle(text, desc)
export const aiGenerateImage = (prompt) => api.aiGenerateImage(prompt)
export const saveTempFile = (buf, name) => api.saveTempFile(buf, name)
export const saveFileDialog = (opts) => api.saveFileDialog(opts)
export const writeBase64 = (path, dataUrl) => api.writeBase64(path, dataUrl)
export const createReel = (img, audio, dur) => api.createReel(img, audio, dur)
export const copyFile = (src, dest) => api.copyFile(src, dest)
export const socialSave = (root, path, state) => api.socialSave(root, path, state)
export const socialLoad = (root, path) => api.socialLoad(root, path)
export const socialClear = (root, path) => api.socialClear(root, path)
